import { Product } from '@/types/product';

export const products: Product[] = [
  {
    id: 'mech-keyboard-1',
    name: 'Bàn phím cơ GearHub Pro Gaming',
    description: 'Professional mechanical gaming keyboard with RGB lighting and hot-swappable switches.',
    longDescription: 'The GearHub Pro Mechanical Keyboard is designed for serious gamers who demand the best. Featuring premium hot-swappable switches, customizable RGB lighting, and a durable aluminum frame, this keyboard offers the perfect balance of performance and aesthetics.',
    price: 1800000,
    discount: 15,
    images: [
      'https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg',
      'https://images.pexels.com/photos/3829271/pexels-photo-3829271.jpeg',
      'https://images.pexels.com/photos/2115257/pexels-photo-2115257.jpeg',
      'https://images.pexels.com/photos/4316/technology-computer-chips-gigabyte.jpg',
    ],
    category: 'keyboards',
    inStock: true,
    isNew: true,
    rating: 4.8,
    reviews: 124,
    sold: 315,
    colors: ['#000000', '#FFFFFF', '#FF0000'],
    specs: [
      { name: 'Switch Type', value: 'Hot-swappable mechanical' },
      { name: 'Backlight', value: 'RGB with 16.8 million colors' },
      { name: 'Connection', value: 'USB-C, Wireless (2.4GHz & Bluetooth)' },
      { name: 'Battery Life', value: 'Up to 240 hours' },
      { name: 'Material', value: 'Aluminum frame, PBT keycaps' },
    ],
    date: '2023-09-15',
  },
  {
    id: 'gaming-mouse-1',
    name: 'Chuột chơi game UltraGear Precision',
    description: 'Ultra-lightweight gaming mouse with 26,000 DPI sensor and customizable buttons.',
    price: 900000,
    discount: 0,
    images: [
      'https://images.pexels.com/photos/4316/technology-computer-chips-gigabyte.jpg',
      'https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg',
    ],
    category: 'mice',
    inStock: true,
    rating: 4.6,
    reviews: 89,
    sold: 256,
    colors: ['#000000', '#FFFFFF'],
    specs: [
      { name: 'Sensor', value: 'HERO 26K' },
      { name: 'DPI Range', value: '100-26,000' },
      { name: 'Programmable Buttons', value: '8' },
      { name: 'Weight', value: '63g' },
      { name: 'Connection', value: 'Wired USB / Wireless' },
    ],
    date: '2023-10-20',
  },
  {
    id: 'headset-1',
    name: 'Tai nghe SoundMaster Pro Gaming',
    description: '7.1 Surround Sound headset with noise-canceling microphone and memory foam ear cushions.',
    price: 1200000,
    discount: 10,
    images: [
      'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg',
      'https://images.pexels.com/photos/3394651/pexels-photo-3394651.jpeg',
    ],
    category: 'headsets',
    inStock: true,
    rating: 4.7,
    reviews: 105,
    sold: 289,
    colors: ['#000000', '#FF0000', '#0000FF'],
    specs: [
      { name: 'Sound', value: '7.1 Surround Sound' },
      { name: 'Frequency Response', value: '20Hz - 20kHz' },
      { name: 'Microphone', value: 'Detachable noise-canceling' },
      { name: 'Connectivity', value: 'USB / 3.5mm jack' },
      { name: 'Weight', value: '320g' },
    ],
    date: '2023-08-10',
  },
  {
    id: 'mousepad-1',
    name: 'Lót chuột SpeedSurface XL Gaming',
    description: 'Extra large gaming mousepad with RGB edge lighting and water-resistant surface.',
    price: 350000,
    discount: 0,
    images: [
      'https://images.pexels.com/photos/7915437/pexels-photo-7915437.jpeg',
      'https://images.pexels.com/photos/7915443/pexels-photo-7915443.jpeg',
    ],
    category: 'mousepads',
    inStock: true,
    isNew: true,
    rating: 4.5,
    reviews: 78,
    sold: 210,
    colors: ['#000000', '#333333'],
    specs: [
      { name: 'Dimensions', value: '900mm x 400mm x 4mm' },
      { name: 'Material', value: 'Micro-woven cloth, rubber base' },
      { name: 'Lighting', value: 'RGB, 16.8 million colors' },
      { name: 'Features', value: 'Water-resistant, Non-slip base' },
    ],
    date: '2023-11-05',
  },
  {
    id: 'naruto-figure-1',
    name: 'Mô hình Naruto Uzumaki Sage Mode',
    description: 'Highly detailed Naruto Uzumaki figure in Sage Mode. Limited edition collector\'s item.',
    price: 850000,
    discount: 0,
    images: [
      'https://images.pexels.com/photos/5011647/pexels-photo-5011647.jpeg',
      'https://images.pexels.com/photos/5490778/pexels-photo-5490778.jpeg',
    ],
    category: 'figures',
    inStock: true,
    rating: 4.9,
    reviews: 63,
    sold: 145,
    specs: [
      { name: 'Height', value: '25cm' },
      { name: 'Material', value: 'PVC, ABS' },
      { name: 'Edition', value: 'Limited (5000 pieces)' },
      { name: 'Articulation', value: 'Non-posable' },
    ],
    date: '2023-07-20',
  },
  {
    id: 'onepiece-figure-1',
    name: 'Mô hình Monkey D. Luffy Gear 5',
    description: 'Premium One Piece figure featuring Luffy in Gear 5 transformation. Highly detailed craftsmanship.',
    price: 1200000,
    discount: 5,
    images: [
      'https://images.pexels.com/photos/5490778/pexels-photo-5490778.jpeg',
      'https://images.pexels.com/photos/5011647/pexels-photo-5011647.jpeg',
    ],
    category: 'figures',
    inStock: false,
    rating: 4.9,
    reviews: 48,
    sold: 120,
    specs: [
      { name: 'Height', value: '30cm' },
      { name: 'Material', value: 'PVC, ABS' },
      { name: 'Edition', value: 'Collector\'s Edition' },
      { name: 'Articulation', value: 'Limited posability' },
    ],
    date: '2023-06-15',
  },
  {
    id: 'led-strip-1',
    name: 'Đèn LED RGB cho Gaming Setup',
    description: 'Customizable RGB LED strip with multiple lighting modes and remote control.',
    price: 250000,
    discount: 0,
    images: [
      'https://images.pexels.com/photos/3520644/pexels-photo-3520644.jpeg',
      'https://images.pexels.com/photos/1038916/pexels-photo-1038916.jpeg',
    ],
    category: 'accessories',
    inStock: true,
    rating: 4.3,
    reviews: 92,
    sold: 310,
    specs: [
      { name: 'Length', value: '2m / 6.56ft' },
      { name: 'Power', value: 'USB powered' },
      { name: 'Control', value: 'Remote + App control' },
      { name: 'Modes', value: '20+ lighting effects' },
    ],
    date: '2023-10-10',
  },
  {
    id: 'headset-stand-1',
    name: 'RGB Headset Stand with USB Ports',
    description: 'Headset stand with RGB lighting and built-in USB hub for convenient connectivity.',
    price: 400000,
    discount: 10,
    images: [
      'https://images.pexels.com/photos/1038916/pexels-photo-1038916.jpeg',
      'https://images.pexels.com/photos/3520644/pexels-photo-3520644.jpeg',
    ],
    category: 'accessories',
    inStock: true,
    rating: 4.5,
    reviews: 67,
    sold: 180,
    colors: ['#000000', '#FFFFFF'],
    specs: [
      { name: 'Ports', value: '3x USB 3.0' },
      { name: 'Lighting', value: 'RGB, 16.8 million colors' },
      { name: 'Material', value: 'Aluminum + ABS' },
      { name: 'Power', value: 'USB powered' },
    ],
    date: '2023-09-05',
  },
  {
    id: 'gaming-chair-1',
    name: 'ErgoMax Pro Gaming Chair',
    description: 'Ergonomic gaming chair with adjustable lumbar support, 4D armrests, and reclining function.',
    price: 3500000,
    discount: 15,
    images: [
      'https://images.pexels.com/photos/6962024/pexels-photo-6962024.jpeg',
      'https://images.pexels.com/photos/6962022/pexels-photo-6962022.jpeg',
    ],
    category: 'chairs',
    inStock: true,
    rating: 4.7,
    reviews: 132,
    sold: 185,
    colors: ['#000000', '#FF0000', '#0000FF'],
    specs: [
      { name: 'Material', value: 'PU Leather' },
      { name: 'Weight Capacity', value: '150kg / 330lbs' },
      { name: 'Armrests', value: '4D adjustable' },
      { name: 'Recline', value: '90°-165°' },
      { name: 'Extras', value: 'Neck and lumbar pillows included' },
    ],
    date: '2023-05-20',
  },
  {
    id: 'gaming-desk-1',
    name: 'Bàn chơi game BattleStation Pro',
    description: 'Spacious gaming desk with cable management system, cup holder, and headphone hook.',
    price: 2500000,
    discount: 0,
    images: [
      'https://images.pexels.com/photos/7887150/pexels-photo-7887150.jpeg',
      'https://images.pexels.com/photos/4792731/pexels-photo-4792731.jpeg',
    ],
    category: 'desks',
    inStock: true,
    isNew: true,
    rating: 4.6,
    reviews: 84,
    sold: 120,
    colors: ['#000000', '#333333'],
    specs: [
      { name: 'Dimensions', value: '160cm x 75cm x 76cm' },
      { name: 'Material', value: 'Carbon fiber texture surface, steel frame' },
      { name: 'Weight Capacity', value: '100kg / 220lbs' },
      { name: 'Features', value: 'Cable management, cup holder, headset hook' },
    ],
    date: '2023-11-15',
  },
  {
    id: 'keycaps-set-1',
    name: 'Bộ phím PBT Doubleshot - Chủ đề Galaxy',
    description: 'Premium PBT doubleshot keycaps with cosmic galaxy design. Compatible with Cherry MX switches.',
    price: 450000,
    discount: 0,
    images: [
      'https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg',
      'https://images.pexels.com/photos/3829271/pexels-photo-3829271.jpeg',
    ],
    category: 'accessories',
    inStock: true,
    rating: 4.8,
    reviews: 56,
    sold: 145,
    specs: [
      { name: 'Material', value: 'PBT Doubleshot' },
      { name: 'Profile', value: 'OEM' },
      { name: 'Compatibility', value: 'Cherry MX and clones' },
      { name: 'Included Keys', value: '104 keys + extras' },
    ],
    date: '2023-08-25',
  },
  {
    id: 'switch-tester-1',
    name: 'Mechanical Switch Tester - 12 Types',
    description: 'Test different mechanical switch types before buying your keyboard. Includes 12 popular switches.',
    price: 24.99,
    discount: 0,
    images: [
      'https://images.pexels.com/photos/3829271/pexels-photo-3829271.jpeg',
      'https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg',
    ],
    category: 'accessories',
    inStock: true,
    rating: 4.5,
    reviews: 42,
    sold: 98,
    specs: [
      { name: 'Switches Included', value: '12 different types' },
      { name: 'Types', value: 'Linear, Tactile, Clicky' },
      { name: 'Brands', value: 'Cherry, Gateron, Kailh' },
      { name: 'Material', value: 'Acrylic case' },
    ],
    date: '2023-07-10',
  },
];

export const bestSellers = products.sort((a, b) => b.sold - a.sold).slice(0, 12);